export const routes = {
  HOME: '/',
  ABOUT_US: '/about-us',
  HISTORY: '/history',
  PAST_PRESIDENTS: '/past-presidents',
  COMMITTEE: '/committee',
  MEMBERSHIP: '/membership',
  SPORTS: '/sports',
  LATEST_NEWS: '/latest-news',
  GALLERY: '/gallery',
  GALLERYNUM: '/gallerynum',
  CONTACT_US: '/contact-us',
  LOGIN: '/login/logreg',
  MEMBERREGISTER: '/memberregister',
  MEMBERSHIPFULL: '/memberpackage',
  USERPROFILE: '/UserProfile',

  CRICKET: '/cricket',
  CRICKET_TEAM: '/cricket/teams',
  CLUB_CRICKET: '/cricket/club-cricket',
  CRICKET_PAST_CAPTAINS: '/cricket/past-captains',

  BASKET_BALL: '/basketball',
  BASKET_TEAM: '/basketball/teams',
  CLUB_BASKET_BALL: '/basketball/club-basketball',
  BASKET_PAST_CAPTAINS: '/basketball/past-captains',
};
